Monthly_Project1/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import index_404, index_team, index_testimonial
from account.views import RegisterView, MyLoginView, user_logout
from contact.views import subscribe
from django.conf.urls.static import static
from Monthly_Project1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('service/', include('services.urls')),
    path('contact/', include('contact.urls')),

    path('404/', index_404, name='index_404'),
    path('team/', index_team, name='index_team'),
    path('testimonial/', index_testimonial, name='index_testimonial'),

    path('register/', RegisterView.as_view(), name='register'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),
    path('subscribe/', subscribe, name='subscribe'),

    path('manager/', include('manager.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from .views import index

app_name = 'about'

urlpatterns = [
    path('', index, name='about'),
]

contact/urls.py
from django.urls import path
from .views import index

app_name = 'contact'

urlpatterns = [
    path('', index, name='contact'),
]

home/urls.py
from django.urls import path
from .views import index

app_name = 'home'

urlpatterns = [
    path('', index, name='home'),
]

manager/urls.py
from django.urls import path
from .views import index

app_name = 'manager'

urlpatterns = [
    path('', index, name='manager'),
]

services/urls.py
from django.urls import path
from .views import index

app_name = 'services'

urlpatterns = [
    path('', index, name='services'),
]

templates/footer.html
<!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Address</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>{{ contacts.address }}</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>{{ contacts.phone }}</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>{{ contacts.email }}</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Opening Hours</h4>
                    <h6 class="text-light">Monday - Friday:</h6>
                    <p class="mb-4">09.00 AM - 09.00 PM</p>
                    <h6 class="text-light">Saturday - Sunday:</h6>
                    <p class="mb-0">09.00 AM - 12.00 PM</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Services</h4>
                    <a class="btn btn-link" href="{% url "services:services" %}">Diagnostic Test</a>
                    <a class="btn btn-link" href="{% url "services:services" %}">Engine Servicing</a>
                    <a class="btn btn-link" href="{% url "services:services" %}">Tires Replacement</a>
                    <a class="btn btn-link" href="{% url "services:services" %}">Oil Changing</a>
                    <a class="btn btn-link" href="{% url "services:services" %}">Vacuam Cleaning</a>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                        <br>Distributed By: <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="{% url "home:home" %}">Home</a>
                            <a href="">Cookies</a>
                            <a href="{% url "contact:contact" %}">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

templates/header.html
    <!-- Topbar Start -->
    <div class="container-fluid bg-light p-0">
        <div class="row gx-0 d-none d-lg-flex">
            <div class="col-lg-7 px-5 text-start">
                <div class="h-100 d-inline-flex align-items-center py-3 me-4">
                    <small class="fa fa-map-marker-alt text-primary me-2"></small>
                    <small>{{ contacts.address }}</small>
                </div>
                <div class="h-100 d-inline-flex align-items-center py-3">
                    <small class="far fa-clock text-primary me-2"></small>
                    <small>{{ contacts.work_schedule }}</small>
                </div>
            </div>
            <div class="col-lg-5 px-5 text-end">
                <div class="h-100 d-inline-flex align-items-center py-3 me-4">
                    <small class="fa fa-phone-alt text-primary me-2"></small>
                    <small>{{ contacts.phone }}</small>
                </div>
                <div class="h-100 d-inline-flex align-items-center">
                    <a class="btn btn-sm-square bg-white text-primary me-1" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-sm-square bg-white text-primary me-1" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-sm-square bg-white text-primary me-1" href=""><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-sm-square bg-white text-primary me-0" href=""><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>CarServ - Car Repair HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static "img/favicon.ico" %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@600;700&family=Ubuntu:wght@400;500&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href=" https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href=" https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static "lib/animate/animate.min.css" %}" rel="stylesheet">
    <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">
    <link href="{% static "lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
    
    {% include 'header.html' %}
    
    {% include 'navigation.html' %}
    
    {% block content %}

    {% endblock %}
    
    {% include 'footer.html' %}
    
    
    <!-- JavaScript Libraries -->
    <script src=" https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static "lib/wow/wow.min.js" %}"></script>
    <script src="{% static "lib/easing/easing.min.js" %}"></script>
    <script src="{% static "lib/waypoints/waypoints.min.js" %}"></script>
    <script src="{% static "lib/counterup/counterup.min.js" %}"></script>
    <script src="{% static "lib/owlcarousel/owl.carousel.min.js" %}"></script>
    <script src="{% static "lib/tempusdominus/js/moment.min.js" %}"></script>
    <script src="{% static "lib/tempusdominus/js/moment-timezone.min.js" %}"></script>
    <script src="{% static "lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js" %}"></script>

    <!-- Template Javascript -->
    <script src="{% static "js/main.js" %}"></script>

</body>

</html>

templates/navigation.html
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a href="{% url "home:home" %}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-car me-3"></i>CarServ</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="{% url "home:home" %}" class="nav-item nav-link active">Home</a>
                <a href="{% url "about:about" %}" class="nav-item nav-link">About</a>
                <a href="{% url "services:services" %}" class="nav-item nav-link">Services</a>
                
                {% if user.is_authenticated %}
                    {% for group in user.groups.all %}
                        {% if group.name == "manager" %}
                            <a href="{% url 'manager:manager' %}" class="nav-item nav-link">Manager</a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu fade-up m-0">
                        <a href="{% url "index_team" %}" class="dropdown-item">Technicians</a>
                        <a href="{% url "index_testimonial" %}" class="dropdown-item">Testimonial</a>
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Account</a>
                    <div class="dropdown-menu fade-up m-0">
                        {% if user.is_authenticated %} 
                            <a href="{% url "logout" %}" class="dropdown-item">Logout</a>
                        {% else %}
                            <a href="{% url "login" %}" class="dropdown-item">Login</a>
                            <a href="{% url "register" %}" class="dropdown-item">Register</a> 
                        {% endif %}
                    </div>
                </div>
                <a href="{% url "contact:contact" %}" class="nav-item nav-link">Contact</a>
                <a href="{% url "subscribe" %}" class="nav-item nav-link">Subscribe</a>
            </div>
            <a href="{% url "services:services" %}" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Get A Quote<i class="fa fa-arrow-right ms-3"></i></a>
        </div>
    </nav>
    <!-- Navbar End -->